/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AuthProvider: typeof import('./src/contexts/AuthContext.jsx')['AuthProvider']
  const CVBuilder: typeof import('./src/pages/CVBuilder.jsx')['default']
  const Dashboard: typeof import('./src/pages/Dashboard.jsx')['default']
  const LanguageProvider: typeof import('./src/contexts/LanguageContext.jsx')['LanguageProvider']
  const supabase: typeof import('./src/utils/supabaseClient.js')['supabase']
  const translations: typeof import('./src/utils/translations.js')['default']
  const useAuth: typeof import('./src/contexts/AuthContext.jsx')['useAuth']
  const useLanguage: typeof import('./src/contexts/LanguageContext.jsx')['useLanguage']
  const useTranslation: typeof import('./src/contexts/LanguageContext.jsx')['useTranslation']
}
