/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AuthProvider: typeof import('./contexts/AuthContext.jsx')['AuthProvider']
  const CVBuilder: typeof import('./pages/CVBuilder.jsx')['default']
  const CVPreview: typeof import('./components/CVPreview.jsx')['default']
  const Certifications: typeof import('./components/FormSteps/Certifications.jsx')['default']
  const Courses: typeof import('./components/FormSteps/Courses.jsx')['default']
  const Dashboard: typeof import('./pages/Dashboard.jsx')['default']
  const DownloadModal: typeof import('./components/DownloadModal.jsx')['default']
  const Education: typeof import('./components/FormSteps/Education.jsx')['default']
  const FloatingBar: typeof import('./components/FloatingBar.jsx')['default']
  const Hobbies: typeof import('./components/FormSteps/Hobbies.jsx')['default']
  const Internships: typeof import('./components/FormSteps/Internships.jsx')['default']
  const LanguageProvider: typeof import('./contexts/LanguageContext.jsx')['LanguageProvider']
  const Languages: typeof import('./components/FormSteps/Languages.jsx')['default']
  const MetaTags: typeof import('./utils/MetaTags.jsx')['default']
  const PersonalInfo: typeof import('./components/FormSteps/PersonalInfo.jsx')['default']
  const Sidebar: typeof import('./sections/Sidebar.jsx')['default']
  const Skills: typeof import('./components/FormSteps/Skills.jsx')['default']
  const Topbar: typeof import('./sections/Topbar.jsx')['default']
  const Traits: typeof import('./components/FormSteps/Traits.jsx')['default']
  const WorkExperience: typeof import('./components/FormSteps/WorkExperience.jsx')['default']
  const downloadCV: typeof import('./utils/downloadPDF.js')['downloadCV']
  const en: typeof import('./utils/en.js')['default']
  const getDotLevel: typeof import('./utils/getDotLevel.js')['getDotLevel']
  const nl: typeof import('./utils/nl.js')['default']
  const supabase: typeof import('./utils/supabaseClient.js')['supabase']
  const translations: typeof import('./utils/translations.js')['default']
  const useAuth: typeof import('./contexts/AuthContext.jsx')['useAuth']
  const useDebounce: typeof import('./hooks/useDebounce.js')['default']
  const useDebouncedCallback: typeof import('./hooks/useDebouncedCallback.js')['default']
  const useDebouncedValue: typeof import('./hooks/useDebouncedValue.js')['default']
  const useLanguage: typeof import('./contexts/LanguageContext.jsx')['useLanguage']
  const useSmartSync: typeof import('./hooks/useSmartSync.js')['default']
  const useSupabaseUser: typeof import('./hooks/useSupabaseUser.js')['default']
  const useTranslation: typeof import('./contexts/LanguageContext.jsx')['useTranslation']
  const useUndoRedo: typeof import('./hooks/useUndoRedo.js')['default']
}
